info:
  app:
    name: Bootcamp
    description: Bootcamp People

server:
  port: 8080



spring:
  application:
    name: bootcamp

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mock_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
hibernate:
  version: 5.6.9