-- TABLES
drop table if exists tbl_users CASCADE;
drop table if exists tbl_lutadores CASCADE;

create table tbl_users (
   id bigint generated by default as identity,
    login varchar(255),
    name varchar(255),
    password varchar(255),
    primary key (id)
    );


-- USERS
insert into tbl_users (ID, NAME, LOGIN, PASSWORD)
    values (1, 'Alan', 'alans', 'f1bf226c0d04086df920c5028de9dd26');

insert into tbl_users (ID, NAME, LOGIN, PASSWORD)
    values (2, 'Otavio', 'ocamargo', '7ffcc00c2e1fd78a91e8c4c8477bc6e8');


create table tbl_lutadores (
	id INTEGER generated by default as identity default on null,
	nome VARCHAR(255),
	nacionalidade VARCHAR(50),
	idade INTEGER,
	altura REAL,
	peso REAL,
	quantidade_vitorias INTEGER,
	quantidade_derrotas INTEGER,
	quantidade_empates INTEGER, 
	total_premios NUMERIC(20, 2),
	primary key (id)
);

--LUTADORES
INSERT INTO TBL_LUTADORES (nome, nacionalidade, idade, altura, peso, quantidade_vitorias, quantidade_derrotas, quantidade_empates, total_premios)
    values ('Pretty Boy', 'Frana', 31, 1.75, 68.9, 11, 2, 1, 0);
INSERT INTO TBL_LUTADORES (nome, nacionalidade, idade, altura, peso, quantidade_vitorias, quantidade_derrotas, quantidade_empates, total_premios)
    values ('Putscript', 'Brasil', 29, 1.68, 57.8, 14, 2, 3, 0);
INSERT INTO TBL_LUTADORES (nome, nacionalidade, idade, altura, peso, quantidade_vitorias, quantidade_derrotas, quantidade_empates, total_premios)
    values ('Snapshadow', 'EUA', 35, 1.65, 80.9, 12, 2, 1, 0);
INSERT INTO TBL_LUTADORES (nome, nacionalidade, idade, altura, peso, quantidade_vitorias, quantidade_derrotas, quantidade_empates, total_premios)
    values ('Dead Code', 'Australia', 28, 1.93, 81.6, 13, 0, 2, 0);
INSERT INTO TBL_LUTADORES (nome, nacionalidade, idade, altura, peso, quantidade_vitorias, quantidade_derrotas, quantidade_empates, total_premios)
    values ('UFOCobol', 'Brasil', 37, 1.70, 119.3, 5, 4, 3, 0);
INSERT INTO TBL_LUTADORES (nome, nacionalidade, idade, altura, peso, quantidade_vitorias, quantidade_derrotas, quantidade_empates, total_premios)
    values ('Nerdaart', 'EUA', 30, 1.81, 105.7, 12, 2, 4, 0);

create table tbl_juizes (
	id INTEGER generated by default as identity,
	nome VARCHAR(255),
	nacionalidade VARCHAR(50),
	idade INTEGER,
	total_comissao NUMERIC(20, 2),
	anos_experiencia INTEGER,
	primary key (id)
);
create table tbl_lutas (
	id INTEGER generated by default as identity,
	id_lutador_desafiante INTEGER,
	id_lutador_desafiado INTEGER,
	quantidade_rounds INTEGER,
	aprovada BOOLEAN,
	valor_premio_luta NUMERIC(20, 2),
	percentual_comissao_juiz REAL,
	id_juiz INTEGER,
	realizada BOOLEAN,
	primary key (id),
	FOREIGN KEY(id_lutador_desafiante) REFERENCES TBL_LUTADORES(ID),
	FOREIGN KEY(id_lutador_desafiado) REFERENCES TBL_LUTADORES(ID),
	FOREIGN KEY(id_juiz) REFERENCES TBL_JUIZES(ID)
);
